env = Environment(
    CC = 'g++',
    CCFLAGS = '-pthread -g -std=c++1z -Wall -Wextra -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wrestrict -Wuseless-cast -Wformat=2'
)


env.Program('mvc-from-scons','main.cpp')